# Generated by Django 3.0.6 on 2020-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_auto_20201103_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousdonation',
            name='checksum_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='regulardonation',
            name='checksum_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
