# Generated by Django 3.0.6 on 2020-11-06 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_auto_20201103_2236'),
    ]

    operations = []
