# Generated by Django 3.0.6 on 2020-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0005_auto_20201106_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousdonation',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='regulardonation',
            old_name='id',
            new_name='uuid',
        ),
    ]
