# Generated by Django 3.0.6 on 2020-11-06 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0007_auto_20201106_1645'),
    ]

    operations = []
