# Generated by Django 3.0.6 on 2020-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0008_auto_20201106_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anonymousdonation',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Regulardonation',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
