# Generated by Django 3.0.6 on 2020-11-06 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trust', '0009_auto_20201106_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymousdonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipcode', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('checksum_id', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Regulardonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('checksum_id', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
